version: '3.8'

services:
  backend:
    image: lahiru98s/lighthouse-sv:latest
    container_name: lighthouse-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./settings.json:/app/settings.json
    restart: always
    networks:
      - lighthouse-net

  frontend:
    image: lahiru98s/lighthouse-ui:latest
    container_name: lighthouse-frontend
    ports:
      - "8066:80"
    depends_on:
      - backend
    restart: always
    networks:
      - lighthouse-net

networks:
  lighthouse-net:
