version: '3.8'

services:
  backend:
    build: ./server
    container_name: lighthouse-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    expose:
      - "8000"
    networks:
      - lighthouse-net

  frontend:
    build: ./client
    container_name: lighthouse-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - lighthouse-net

networks:
  lighthouse-net:
    driver: bridge
