version: '3.8'

services:
  backend:
    build: ./server
    container_name: lighthouse-backend
    ports:
        - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - lighthouse-net

  frontend:
    build: ./client
    container_name: lighthouse-frontend
    ports:
      - "8066:80"
    depends_on:
      - backend
    restart: always
    networks:
      - lighthouse-net

networks:
  lighthouse-net:
    driver: bridge
