services:
  lighthouse:
    image: ghcr.io/nooblk-98/lighthouse:dev
    container_name: lighthouse
    ports:
      - "8066:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks/lighthouse/settings.db:/app/data/settings.db
    restart: always